import Head from "next/head"
import Player from "@/components/player"
import ModalFormSecond from "@/components/form/ModalFormSecond"

export default function Home() {
  const track = {
    id: 1,
    author: "Pham feat. Filip",
    name: "Squaad",
    src: "/audio/pham.mp3",
  }

  return (
    <>
      <Head>
        <title>
          {track.author} - {track.name}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Player track={track} />
      <div className="form-position">
        <ModalFormSecond
          color={"success"}
          label={"Успешно"}
          value={"Введите текст"}
        />
        <ModalFormSecond
          color={"primary"}
          label={"Обязательно"}
          value={"Введите текст"}
        />
        <ModalFormSecond
          color={"info"}
          label={"Информация"}
          value={"Введите текст"}
        />
        <ModalFormSecond
          color={"warning"}
          label={"Ошибка"}
          value={"Введите текст"}
        />
      </div>
    </>
  )
}
