import Head from 'next/head';
import Button from '@/ui/components/Button';
import Registration from "@/ui/components/form/Registration"
export default function Home() {
  return (
    <>
      <Head>
        <title>---</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>


      {/* <div className="form-position">
        <Registration value={"Имя"} type={"text"} />
      </div>
      <Button />
      <Button text={'text'} type={'button'} style={'orange'} />
      <Button
        text={'link'}
        type={'button'}
        style={'grey'}
        link={'https://ya.ru/'}
      />
      <Button text={'link'} type={'submit'} link={'https://ya.ru/'} /> */}
    </>
  )
}
