import Head from 'next/head';
import Player from '@/components/player';

export default function Home() {
  const track = {
    id: 1,
    author: 'breathe.',
    name: 'Are You All Good',
    src: '/audio/breathe.mp3'
  }

  return (
    <>
      <Head>
        <title>Учебный проект</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Player track={track} />
    </>
  );
}
