import Head from 'next/head';
import Player from '@/components/player';

export default function Home() {
  return (
    <>
      <Head>
        <title>Учебный проект</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Player />
    </>
  );
}
